import { StyleSheet } from 'react-native';

/** Shared transparent-on-solar-background UI (panels, text, inputs). */
export const onBgStyles = StyleSheet.create({
  screenSafe: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  screenContent: {
    padding: 16,
    gap: 12,
    paddingBottom: 28,
  },
  homeOnBg: {
    flex: 0,
    alignSelf: 'stretch',
    gap: 10,
    backgroundColor: 'transparent',
  },
  onBgPanel: {
    borderWidth: 3,
    borderColor: 'rgba(255, 255, 255, 0.92)',
    borderRadius: 10,
    padding: 12,
    gap: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.15)',
  },
  onBgPanelSelected: {
    borderColor: '#bbf7d0',
    borderWidth: 3,
  },
  onBgPanelNight: {
    borderColor: 'rgba(200, 215, 240, 0.95)',
  },
  onBgPanelInner: {
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.8)',
    borderRadius: 8,
    padding: 10,
    gap: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.12)',
  },
  onBgAlertPanel: {
    borderColor: '#ffb4a8',
  },
  onBgAlertText: {
    fontSize: 16,
    fontWeight: '700',
    textShadowColor: 'rgba(0, 0, 0, 0.65)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  onBgErrorText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#fecaca',
    textShadowColor: 'rgba(0, 0, 0, 0.65)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  onBgTitle: {
    fontSize: 22,
    fontWeight: '800',
    textShadowColor: 'rgba(0, 0, 0, 0.65)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  onBgHeading: {
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 26,
    textShadowColor: 'rgba(0, 0, 0, 0.65)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  onBgSectionTitle: {
    fontSize: 17,
    fontWeight: '800',
    lineHeight: 24,
    textShadowColor: 'rgba(0, 0, 0, 0.65)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  onBgHighlight: {
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 24,
    textShadowColor: 'rgba(0, 0, 0, 0.7)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  onBgBody: {
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 24,
    textShadowColor: 'rgba(0, 0, 0, 0.7)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  onBgMuted: {
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 22,
    opacity: 0.95,
    textShadowColor: 'rgba(0, 0, 0, 0.65)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  onBgHourly: {
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 22,
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  onBgLabel: {
    fontSize: 15,
    fontWeight: '700',
    textShadowColor: 'rgba(0, 0, 0, 0.65)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  onBgInput: {
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.8)',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 10,
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
  },
  onBgDropdown: {
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.8)',
    borderRadius: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    overflow: 'hidden',
  },
  onBgCityRow: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255, 255, 255, 0.35)',
    gap: 2,
  },
  onBgActionButton: {
    alignSelf: 'flex-start',
    marginTop: 6,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 8,
    backgroundColor: 'rgba(10, 126, 164, 0.9)',
  },
  onBgActionButtonSelected: {
    backgroundColor: 'rgba(31, 122, 52, 0.92)',
  },
  onBgActionButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  onBgOutlineButton: {
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 8,
    alignItems: 'center',
    paddingVertical: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
  },
  onBgOutlineButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  onBgDangerButton: {
    borderWidth: 2,
    borderColor: '#ffb4a8',
    borderRadius: 8,
    alignItems: 'center',
    paddingVertical: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
  },
  onBgDangerButtonText: {
    color: '#ffe8e4',
    fontSize: 15,
    fontWeight: '700',
  },
  onBgSocBarTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.5)',
    overflow: 'hidden',
    marginTop: 2,
    marginBottom: 2,
  },
  onBgBadge: {
    alignSelf: 'flex-start',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.75)',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 2,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    fontWeight: '700',
    fontSize: 14,
  },
  buttonPressed: { opacity: 0.85 },
});
